export const TEST_SUBTITLES = {
  "CBC":"Complete Blood Count – RBC, WBC, Platelets & Hemoglobin",
  "Complete Blood Count":"Complete Blood Count (CBC) – RBC, WBC, Platelets & Hemoglobin",
  "Complete Blood Count (CBC)":"Complete Blood Count (CBC) – RBC, WBC, Platelets & Hemoglobin",
  "Hemoglobin":"Hemoglobin (Hb) – Anemia & Oxygen Carrying Capacity",
  "LFT":"Liver Function Test – SGOT, SGPT, Bilirubin & Alkaline Phosphatase",
  "Liver Function Test":"Liver Function Test (LFT) – SGOT, SGPT, Bilirubin & Alkaline Phosphatase",
  "Liver Function Test (LFT)":"Liver Function Test (LFT) – SGOT, SGPT, Bilirubin & Alkaline Phosphatase",
  "KFT":"Kidney Function Test – Creatinine, Urea, Uric Acid & Electrolytes",
  "Kidney Function Test":"Kidney Function Test (KFT) – Creatinine, Urea, Uric Acid & Electrolytes",
  "Kidney Function Test (KFT)":"Kidney Function Test (KFT) – Creatinine, Urea, Uric Acid & Electrolytes",
  "Thyroid Profile":"Thyroid Profile – Total T3, T4 & Thyroid Stimulating Hormone (TSH)",
  "Thyroid Profile Total":"Thyroid Profile Total – T3, T4 & TSH",
  "TSH":"Thyroid Stimulating Hormone (TSH) – Thyroid Function Screening",
  "T3 T4 TSH":"Thyroid Profile – T3, T4 & Thyroid Stimulating Hormone (TSH)",
  "Lipid Profile":"Lipid Profile – Total Cholesterol, HDL, LDL, VLDL & Triglycerides",
  "Cholesterol":"Total Cholesterol – Cardiovascular Risk Assessment",
  "Blood Sugar Fasting":"Fasting Blood Glucose (FBG) – Diabetes Screening",
  "Blood Sugar PP":"Post-Prandial Blood Glucose (PPBS) – Post-Meal Diabetes Check",
  "Blood Sugar Random":"Random Blood Sugar (RBS) – Spot Glucose Measurement",
  "HbA1c":"Glycated Hemoglobin (HbA1c) – 3-Month Average Blood Sugar",
  "Vitamin D":"Vitamin D (25-Hydroxy) – Bone Health & Immunity Panel",
  "Vitamin D3":"Vitamin D3 (Cholecalciferol) – Bone Density & Immunity",
  "Vitamin B12":"Vitamin B12 (Cobalamin) – Nerve & Red Blood Cell Health",
  "Iron Studies":"Iron Studies – Serum Iron, TIBC & Ferritin",
  "Ferritin":"Serum Ferritin – Iron Storage & Deficiency Screening",
  "Urine Routine":"Urine Routine & Microscopy – Kidney & Bladder Health Panel",
  "Urine Analysis":"Urinalysis – Physical, Chemical & Microscopic Examination",
  "HBsAg":"Hepatitis B Surface Antigen (HBsAg) – Hepatitis B Screening",
  "HIV":"HIV 1 & 2 Antibody Test – Retroviral Infection Screening",
  "Dengue NS1":"Dengue NS1 Antigen – Early Dengue Fever Detection",
  "Malaria":"Malaria Antigen Test – P. vivax & P. falciparum Detection",
  "Typhoid":"Widal Test / Typhoid Antibody – Typhoid Fever Screening",
  "CRP":"C-Reactive Protein (CRP) – Inflammation & Infection Marker",
  "ESR":"Erythrocyte Sedimentation Rate (ESR) – Inflammation Screening",
  "Calcium":"Serum Calcium – Bone, Nerve & Muscle Function Panel",
  "Phosphorus":"Serum Phosphorus – Bone Metabolism & Kidney Function",
  "Uric Acid":"Serum Uric Acid – Gout & Kidney Stone Risk Assessment",
  "Creatinine":"Serum Creatinine – Kidney Function & Filtration Rate",
  "Blood Urea":"Blood Urea Nitrogen (BUN) – Kidney Waste Filtration Check",
  "SGOT":"SGOT (AST) – Liver & Heart Muscle Enzyme Level",
  "SGPT":"SGPT (ALT) – Liver Cell Damage & Hepatitis Marker",
  "Bilirubin Total":"Bilirubin Total – Liver Function & Jaundice Screening",
  "Prolactin":"Serum Prolactin – Hormonal & Fertility Assessment",
  "FSH":"Follicle Stimulating Hormone (FSH) – Fertility Panel",
  "LH":"Luteinizing Hormone (LH) – Ovulation & Hormone Balance",
  "Testosterone":"Serum Testosterone – Male Hormonal Health Panel",
  "PSA":"Prostate Specific Antigen (PSA) – Prostate Cancer Screening",
  "CA 125":"Cancer Antigen 125 (CA-125) – Ovarian Cancer Marker",
  "CEA":"Carcinoembryonic Antigen (CEA) – Colorectal Cancer Marker",
  "AFP":"Alpha Fetoprotein (AFP) – Liver & Testicular Cancer Marker",
  "Prothrombin Time":"Prothrombin Time (PT/INR) – Blood Clotting Function Test",
  "APTT":"Activated Partial Thromboplastin Time – Clotting Disorder Screen",
  "Platelet Count":"Platelet Count – Bleeding & Clotting Disorder Screening",
  "Dengue":"Dengue Fever Panel – NS1 Antigen, IgM & IgG Antibodies",
  "Stool Routine":"Stool Routine & Microscopy – Gut Infection & Parasite Screen",
  "Throat Swab":"Throat Swab Culture – Bacterial Infection & Sensitivity",
  "Sputum AFB":"Sputum AFB Smear – Tuberculosis (TB) Detection",
  "ECG":"Electrocardiogram (ECG) – Heart Rhythm & Electrical Activity",
  "Echo":"Echocardiogram – Heart Structure & Function Assessment",
  "Chest X-Ray":"Chest X-Ray – Lung, Heart & Rib Cage Imaging",
  "Ultrasound Abdomen":"Ultrasound Abdomen – Liver, Kidney & Abdominal Organ Scan",
  "Basic Health Checkup":"Basic Health Checkup – CBC, LFT, KFT, Blood Sugar & Lipid Profile",
  "Comprehensive Health Checkup":"Comprehensive Health Checkup – Full Body Organ Function Panel",
  "Aarogyam Basic":"Aarogyam Basic – 38 Wellness Parameters for Complete Body Health",
  "Aarogyam 1.3":"Aarogyam 1.3 – 72 Tests Including Vitamins, Hormones & Organ Function",
  "Full Body Checkup":"Full Body Checkup – 80+ Parameters Covering All Major Organ Systems",
  "Women Health Checkup":"Women's Health Checkup – Hormones, Thyroid, Vitamins & Blood Panel",
  "Men Health Checkup":"Men's Health Checkup – Testosterone, PSA, Heart & Organ Function",
  "Senior Citizen Checkup":"Senior Citizen Checkup – Bones, Heart, Kidney, Thyroid & Diabetes Panel",
  "Diabetes Package":"Diabetes Care Package – HbA1c, FBG, PPBS, Kidney & Lipid Profile",
  "Heart Package":"Cardiac Risk Package – Lipid Profile, ECG, CRP & Homocysteine",
  "Arthritis Package":"Arthritis Panel – RA Factor, CRP, ESR, Uric Acid & Calcium",
  "PCOD Package":"PCOD / PCOS Hormonal Panel – LH, FSH, Testosterone & Insulin",
  "Anemia Package":"Anemia Profile – CBC, Iron Studies, Ferritin, B12 & Folate",
};
export function getTestSubtitle(name) {
  if (!name) return "";
  if (TEST_SUBTITLES[name]) return TEST_SUBTITLES[name];
  // fuzzy: check if any key is contained in the name
  const lower = name.toLowerCase();
  for (const [key, val] of Object.entries(TEST_SUBTITLES)) {
    if (lower.includes(key.toLowerCase()) && key.length > 4) return val;
  }
  return name;
}
